// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nubfoaatkogyicwywatm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51YmZvYWF0a29neWljd3l3YXRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODg1OTcsImV4cCI6MjA1OTk2NDU5N30.MYEopAH_oCy3Sh1-JBw8v93jiwxzdjaRRLQLC53YXDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);